import type { MailAccount, MailMessage } from '../shared/models'

export const accounts: MailAccount[] = [
  { id: 'personal', provider: 'gmail', name: 'Personal', email: 'alex@example.com', color: '#d95d50', unread: 5 },
  { id: 'outlook', provider: 'outlook', name: 'Outlook', email: 'alex@example.com', color: '#3977c9', unread: 2 }
]

export const messages: MailMessage[] = [
  { id: 'm1', threadId: 't1', accountId: 'personal', sender: { name: 'Maya Chen', email: 'maya@fieldnotes.studio', initials: 'MC' }, recipients: ['alex@example.com'], subject: 'The Copenhagen notes', preview: 'I finally organized the photographs and the little list of places we talked about…', body: ['Hi Alex,', 'I finally organized the photographs and the little list of places we talked about. The bakery near Frederiksberg was every bit as good the second time around.', 'I attached the short field guide. There are a few quiet corners in it that I think you would love—especially the reading room by the canal.', 'Let me know when you have a free evening. I’d love to hear what you’re building.'], receivedAt: '2026-08-25T09:42:00', timeLabel: '9:42 AM', unread: true, starred: true, labels: ['Travel'], attachments: [{ id: 'a1', name: 'Copenhagen field notes.pdf', size: '2.4 MB', kind: 'pdf' }] },
  { id: 'm2', threadId: 't2', accountId: 'outlook', sender: { name: 'Elliot Reyes', email: 'elliot@northline.co', initials: 'ER' }, recipients: ['alex@example.com'], subject: 'A small change to Thursday', preview: 'Could we move our call by thirty minutes? Everything else on the agenda stays…', body: ['Hello Alex,', 'Could we move our call by thirty minutes, to 3:30? Everything else on the agenda stays exactly the same.', 'No rush—just send me a quick yes when you see this.', 'Best,\nElliot'], receivedAt: '2026-08-25T08:18:00', timeLabel: '8:18 AM', unread: true, starred: false },
  { id: 'm3', threadId: 't3', accountId: 'personal', sender: { name: 'Paper & Type', email: 'letters@paperandtype.com', initials: 'P&T' }, recipients: ['alex@example.com'], subject: 'August reading list', preview: 'Five essays about attention, cities, and the pleasure of making things slowly.', body: ['This month: five essays about attention, cities, and the pleasure of making things slowly.', 'We hope you find something worth keeping.'], receivedAt: '2026-08-24T18:03:00', timeLabel: 'Yesterday', unread: false, starred: false, labels: ['Reading'] },
  { id: 'm4', threadId: 't4', accountId: 'personal', sender: { name: 'Noah Williams', email: 'noah.w@example.com', initials: 'NW' }, recipients: ['alex@example.com'], subject: 'Re: The bookshelf', preview: 'The oak sample is the one. Warm without being too orange, and it will age beautifully…', body: ['The oak sample is the one. Warm without being too orange, and it will age beautifully.', 'I’ll send the final measurements tomorrow morning.'], receivedAt: '2026-08-23T14:25:00', timeLabel: 'Sat', unread: false, starred: true, attachments: [{ id: 'a2', name: 'oak-sample.jpg', size: '1.1 MB', kind: 'image' }] },
  { id: 'm5', threadId: 't5', accountId: 'outlook', sender: { name: 'Microsoft', email: 'account-security-noreply@accountprotection.microsoft.com', initials: 'M' }, recipients: ['alex@example.com'], subject: 'Your weekly account summary', preview: 'Here is a summary of the recent activity associated with your account…', body: ['Here is a summary of the recent activity associated with your account.', 'No action is required.'], receivedAt: '2026-08-22T10:05:00', timeLabel: 'Fri', unread: false, starred: false },
  { id: 'm6', threadId: 't6', accountId: 'personal', sender: { name: 'Leila Haddad', email: 'leila.h@example.com', initials: 'LH' }, recipients: ['alex@example.com'], subject: 'Dinner next week?', preview: 'There is a new place near the park that looks wonderfully unambitious. Tuesday?', body: ['There is a new place near the park that looks wonderfully unambitious—in the best way.', 'Would Tuesday evening work?'], receivedAt: '2026-08-20T20:40:00', timeLabel: 'Aug 20', unread: true, starred: false }
]
